### PR TITLE
Spacing on side

### PR DESCRIPTION
**Pull request by 0nn0**
Is there a way we can achieve the following, without making modifications to the newsletter.js (except for the viewport tag, we can change this one)?

Initial state:
initial-state

Zoomed-in state:
zoomed-in-state

How can we achieve this? Any idea or suggestion?

### CODE REVIEW

**Comment by iou90** [comment]
Please check the last commit of the branch "spacingOnSide".
It can be done without modifications to the "newsletter.js", but it clearly needs to adjust the style for the different sources specifically.

**Comment by 0nn0** [comment]
Thanks for your work!

Tested it, but the first thing I noticed is that the scaling is a bit off...

Correct scaling:
Screen Shot 2020-01-13 at 10 43 46 AM

Incorrect scaling:
Screen Shot 2020-01-13 at 10 37 31 AM

2. When zoomed-in, it does not use the spacing on the side. Ideally it would use also the spacing on the side. See "Zoomed-in state:" in my first message in this PR.
Screen Shot 2020-01-13 at 10 34 42 AM

Any idea what this is being caused by?

**Comment by 0nn0** [comment]
Second question: Is there anyway that when you start zooming-in, that the full-width of the device is used?

Instead of this:
Screen Shot 2020-01-13 at 10 34 42 AM

It does this:
zoomed-in-state

**Comment by iou90** [comment]
1. Because the origin scale of this page was smaller than 1.0 (screen.width / window.innerWidth < 1), please check the last commit.
``` javascript
// 500 -> min-width of #doc in newsletter
viewportContent={`initial-scale=${Dimensions.get('window').width / 500}`}
```

2. Actually the full width of the device is used as rnahw component using the width of screen.
zooming using the width of screen

**Comment by 0nn0** [comment]
Hi @iou90,

The problem is that we can not customize the viewport meta-tag for each message. 

The ideal scenario would be that content rendered in `react-native-autoheight-webview` would at be identical to when rendered in `react-native-webview`. All I as a user would expect is that `rnwah` would help me to automatically set the height, but other than that render identically.

Currently it renders differently.

comparison

How can we achieve the identical result? What if `rnwah` would base the scaling on the webview-width instead of the screen-width?

**Comment by iou90** [comment]
1. As I mentioned before, it has to adjust the style for the different sources specifically.
2. All the things we talked about previously suppose to achieve the effects in these gifs from the PR.  The difference between the two images (identical issue) looks irrelevant to this PR, can you provide the props of rnahw about this issue?

**Pull request merged**
