### PR TITLE
Add scrollEnabled bool config with defaultProps

### PR DESCRIPTION
**Pull request by rickychowhk01**

### CODE REVIEW

**Comment by iou90** [comment]
Set scrollEnabled to true may cause some problems, what is it purpose or can you provide a case?

**Comment by rickychowhk01** [comment]
Hi iou90,

thanks for reviewing my PR, I updated comment into index.ios.js and waiting
for your approve

Cheers,

Ricky Chow

Application Architect


E/ rickychow@hk01.com
T/ 852 3582 8347
M/ 852 5548 5434
W/ www.hk01.com


香港零一媒體有限公司 WeMedia01 (HK) Ltd
香港荃灣沙咀道6號嘉達環球中心11樓
11/F, The Octagon, No. 6 Sha Tsui Road, Tsuen Wan, N.T. HK

[image: cid:image009.png@01D1C7CB.DA998E00]
<https://play.google.com/store/apps/details?id=com.hk01.news_app>[image:
cid:image010.png@01D1C7CB.DA998E00] <https://appsto.re/hk/2dQPab.i>

2018-07-09 13:13 GMT+08:00 iou90 <notifications@github.com>:

**Comment by iou90** [comment]
Currently I am working with this pr (#56) and other features/fixes, as the same time I have already added scrollEnabled prop, so closed, thank you.

**Comment by rickychowhk01** [comment]
Wow, thanks iou90, you did a great job!!

**Pull request closed without merging**
