### PR TITLE
failing to render quora newsletter html

### PR DESCRIPTION
**Pull request by juliangruber**
This PR contains an HTML source that fails to render properly, a newsletter from Quora. When the webview is first initialized with it, it's height is calculated as 0:

Screenshot 2019-10-22 at 14 59 59

Then after switching to a known good HTML source, things look ok:

Screenshot 2019-10-22 at 15 00 59

Switching back to quora, it now renders, but still has the same height as the previous HTML source, which is not the correct height:

Screenshot 2019-10-22 at 15 01 31

This is how the page looks in Safari:

67213033-97d41b80-f41d-11e9-8d24-51d4c7edbf97

### CODE REVIEW

**Comment by iou90** [comment]
Should be fixd on @1.2.3
https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.2.3

**Comment by juliangruber** [comment]
Thank you so much, that fixed it! <3

**Comment by juliangruber** [comment]
I found another site that renders differently than in Safari:

Screenshot 2019-11-04 at 14 55 25

The width is off, which I think affects the scaling. This scaling is all a bit mysterious to me!

**Comment by iou90** [comment]
The scaling has some differences between rendering in safari and in react-native-webview.
To get the scaling correct you may have to remove all min-width styles of your html codes.

**Comment by juliangruber** [comment]
Right, for a fitting comparison it should be compared with the `react-native-webview`. I've changed the demo to use that instead and it does render more similar to safari:

Screenshot 2019-11-13 at 11 34 49

eg

```js
      <WebView
        customStyle={heightStyle}
        onError={onError}
        onLoad={onHeightLoad}
        onLoadStart={onHeightLoadStart}
        onLoadEnd={onHeightLoadEnd}
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        onSizeUpdated={setHeightSize}
        source={{ html: heightHtml }}
        customScript={heightScript}
        onMessage={onMessage}
        style={{ width: 415, height: 900 }}
      />
```

**Comment by iou90** [comment]
@juliangruber 
Should be fixed on @1.3.0, 
`scalesPageToFit={true}`
https://github.com/iou90/react-native-autoheight-webview/releases/tag/v1.3.0

**Comment by juliangruber** [comment]
confirmed, it works <3 <3

**Pull request closed without merging**
